### ISSUE TITLE
]cider.version fails with a value error if Expose->Root properties is not ticked in Dyalog

### ISSUE THREAD

**Issue by dyavc** [aplteam/Cider#1] opened 2021-10-15 14:24 UTC
]cider.version fails with a value error if Expose->Root properties is not ticked in Dyalog

]cider.version
* Command Execution Failed: VALUE ERROR

      ]cider.version
  Cider  0.4.0+109  2021-10-13    

Try to get the aplversion this way instead:  
'.' ⎕wg 'aplversion'

**Comment by aplteam** [comment] 2021-10-15 18:25
Fixed in 0.4.1

**Closed as completed by aplteam** 2021-10-15 18:25 UTC

**Comment by mbaas2** [comment] 2023-12-06 16:50
This issue has come back and it also affects `CreateProject`  (and possibly others that I didn't try)

**Comment by aplteam** [comment] 2023-12-06 16:58
Cannot reproduce. Which version of Cider are you using?

Please switch on `debug` and send over the precise error message.
